snowcap_admin_default_index:
    path:     ""
    defaults: { _controller: SnowcapAdminBundle:Default:index }

snowcap_admin_reorderablecontent_reorder:
    path:     /reorder/{code}/{locale}
    defaults: { _controller: SnowcapAdminBundle:ReorderableContent:reorder, locale: null }

snowcap_admin_markdown:
    path:     /markdown
    defaults: { _controller: SnowcapAdminBundle:Default:markdown }

snowcap_admin_switch_locale:
    path:     /switch-locale/{locale}
    defaults: { _controller: SnowcapAdminBundle:Default:switchLocale }

snowcap_admin_wysiwyg_browser:
    path:     /wysiwyg/browser
    defaults: { _controller: SnowcapAdminBundle:Wysiwyg:browser }

snowcap_admin_cataloguetranslation_index:
    path:     /catalogue-translation/{catalogue}/{locale}
    defaults: { _controller: SnowcapAdminBundle:CatalogueTranslation:index, catalogue: messages, locale: null }

snowcap_admin_widget_delete_item:
    path:     /widget/delete-item
    defaults: { _controller: SnowcapAdminBundle:Widget:deleteItem }

snowcap_admin_widget_content_changed:
    path:     /widget/content-changed
    defaults: { _controller: SnowcapAdminBundle:Widget:contentChanged }

snowcap_admin_upload:
    path:     /upload
    defaults: { _controller: SnowcapAdminBundle:Upload:upload }

snowcap_admin_login:
    path:     /login
    defaults:  { _controller: SnowcapAdminBundle:Security:login }

snowcap_admin_login_check:
    path:     /login_check

snowcap_admin_logout:
    path:     /logout

snowcap_admin_extra:
    resource: .
    type: snowcap_admin_extra